services:
  accounts:
    image: gaganchhabra25/accounts:s6
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: accounts
  loans:
    image: gaganchhabra25/loans:s6
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: loans
  cards:
    image: gaganchhabra25/cards:s6
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: cards
  configserver:
    image: gaganchhabra25/configserver:s6
    container_name: configserver-microservice
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"
