services:
  accounts:
    image: gaganchhabra25/accounts:s6
    container_name: accounts-microservice
    depends_on:
      configserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: accounts
  loans:
    image: gaganchhabra25/loans:s6
    container_name: loans-microservice
    depends_on:
      configserver:
        condition: service_healthy
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: loans
  cards:
    image: gaganchhabra25/cards:s6
    container_name: cards-microservice
    depends_on:
      configserver:
        condition: service_healthy
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: cards
  configserver:
    image: gaganchhabra25/configserver:s6
    container_name: configserver-microservice
    depends_on:
      rabbit:
        condition: service_healthy
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"
