spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///D://Gagan//Study Material//Microservices//config-files"
#          search-locations: "classpath:/config"

server:
  port: 8071
