spring:
  application:
    name: "configserver"
    profiles:
      active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GaganChhabra25/microservices-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
 # profiles:
 #   active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: "file:///D://Gagan//Study Material//Microservices//config-files"
#          search-locations: "classpath:/config"

server:
  port: 8071
